language: node_js
node_js:
- '0.10'
- '0.11'
before_script:
- npm install -g bower grunt-cli
- bower install
services: mongodb
# deploy:
#   provider: heroku
#   api_key:
#     secure: Pu3nqcQUsvU0bDIMdw3/PZ0n+xaibodt+F1uunovHsozyt2SiprH0m6tLOB3bnaEagWMaPo/Du+GPwhsXgYwkfv+X40T36UA8DYQCBbxOqNzngA7qlQFoGHT8BNuEC3RyKtEJ1E6rdwAAmhsYQhwpcxyPpHYNs4Aa1RNCkDrGis=
#   app: YeoMEAN
#   on:
#     repo: bman4789/YeoMEAN
